### ISSUE TITLE
Cocoapods and Sample Project

### ISSUE THREAD

**Issue by YoomamaFTW** [Andrew-Chen-Wang/RichEditorView#6]
The current sample project is a copy pasta like the rest of this repo. In the future, I'd like to get started with cocoa pods and stuff, but a main concern of mine is the sample project. I'd like for it to... well work out of the box with an Xcode project. Since I'm not linking my name anywhere, would someone mind creating all the necessary xcodeproj and the package dependencies?

**Comment by rbarbish** [comment]
This would be great...there are many missing dependencies and errors in this repository - offline, checkbox, duplicate method declarations, etc.

**Comment by Kedar-27** [comment]
can you add this repo in  hactober, i will create spm support for this

**Comment by Andrew-Chen-Wang** [comment]
I will do so next year if it isn't an absolute shit show.

**Comment by Andrew-Chen-Wang** [comment]
This issue will be closed when I publish this to SPM after thorough testing.
