### ISSUE TITLE
Toolbar on iOS <13 isn't working

### ISSUE THREAD

**Issue by ktoosiu** [Andrew-Chen-Wang/RichEditorView#8]
when I'm running editor on phone/ simulator with iOS 12 I don't have toolbar, any workaround to fix id?

**Comment by ktoosiu** [comment]
so I've found solution myself, it's probably not very pretty but it's working. 
I extend WKWebView 
`var ToolbarHandle: UInt8 = 0

		extension WKWebView {
			func addInputAccessoryView(toolbar: UIView?) {
				guard let toolbar = toolbar else {return}
				objc_setAssociatedObject(self, &ToolbarHandle, toolbar, objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN_NONATOMIC)

				var candidateView: UIView? = nil
				for view in self.scrollView.subviews {
					let description : String = String(describing: type(of: view))
					if description.hasPrefix("WKContent") {
						candidateView = view
						break
					}
				}
				guard let targetView = candidateView else {return}
				let newClass: AnyClass? = classWithCustomAccessoryView(targetView: targetView)

				guard let targetNewClass = newClass else {return}

				object_setClass(targetView, targetNewClass)
			}

			func classWithCustomAccessoryView(targetView: UIView) -> AnyClass? {
				guard let _ = targetView.superclass else {return nil}
				let customInputAccesoryViewClassName = "_CustomInputAccessoryView"

				var newClass: AnyClass? = NSClassFromString(customInputAccesoryViewClassName)
				if newClass == nil {
					newClass = objc_allocateClassPair(object_getClass(targetView), customInputAccesoryViewClassName, 0)
				} else {
					return newClass
				}

				let newMethod = class_getInstanceMethod(WKWebView.self, #selector(WKWebView.getCustomInputAccessoryView))
				class_addMethod(newClass.self, #selector(getter: WKWebView.inputAccessoryView), method_getImplementation(newMethod!), method_getTypeEncoding(newMethod!))

				objc_registerClassPair(newClass!)

				return newClass
			}

			@objc func getCustomInputAccessoryView() -> UIView? {
				var superWebView: UIView? = self
				while (superWebView != nil) && !(superWebView is WKWebView) {
					superWebView = superWebView?.superview
				}

				guard let webView = superWebView else {return nil}

				let customInputAccessory = objc_getAssociatedObject(webView, &ToolbarHandle)
				return customInputAccessory as? UIView
			}
		}
`

and in RichEditorView class I changed inputAccessoryView to 
`	open override var inputAccessoryView: UIView? {
		get {
			if #available(iOS 13.0, *) {
				return webView.accessoryView
			} else {
				return webView.getCustomInputAccessoryView()
			}
		}
		set {
			if #available(iOS 13.0, *) {
				webView.accessoryView = newValue
			} else {
				webView.addInputAccessoryView(toolbar: newValue) }
		}
	}`

so on iOS 13 it's using regular accessoryView like it should and on earlier versions it's using hacky workaraund solution (bit simmilar to one used in original library)

**Comment by Andrew-Chen-Wang** [comment]
I haven’t had the time to implement this issue which also occurred on the other WKWebView repo, so thank you for the solution.

I’ll look into a different way in around 2 weeks, but I highly doubt I’ll be importing this into the dev library. I don’t like hacks, especially since Apple is really good at getting people to update to the latest iOS. (I use some website that shows the latest distribution).

But thanks again!

**Comment by ktoosiu** [comment]
yeah i realize this isn't good solution however I post this workaround if somebody needs to quick fix this. However I'm looking forward if you can find more elegant solution

**Comment by YoomamaFTW** [comment]
I think this is going to remain stale, and I may close it later on since most iOS users are already moving on to iOS 13, especially with the new release of the SE 2nd gen. I'll keep it here until we get 97% iOS 13 users, which should come easily with the SE. I think so far we're at avg 90-95% between all iOS devices?

**Comment by Andrew-Chen-Wang** [comment]
Most users are on iOS 13 and many are on 14 as iPhone 6 users are purchasing new devices and iPhone 6s users are already on iOS 13.
