### ISSUE TITLE
Adding your RichEditorView group has issues building

### ISSUE THREAD

**Issue by brandtdaniels** [Andrew-Chen-Wang/RichEditorView#9]
In **RichEditorOptionItem** Line 162:
_Value of type 'RichEditorView' has no member 'checkbox'_

In **RichEditorView**
Line 358:
_Use of unresolved identifier 'offline'_
Line 360:
_Use of unresolved identifier 'vidURL'_
Line 400:
_Expression of type 'String' is unused_
Line 406:
_Invalid redeclaration of 'addRowToTable()'_

**Comment by YoomamaFTW** [comment]
Interesting. I did this mostly through an SSH terminal into my work computer at the time. Planning on reworking it on Xcode IDE itself sometimes next month.

**Comment by maqiqing** [comment]
same problem..how to fix it?

**Comment by YoomamaFTW** [comment]
@maqiqing This is mostly due to missing code in the JS or undeclared variables. Looking to fix this this month hopefully!

**Comment by shillwil** [comment]
Cmd+A and Ctrl+i in RichEditorView fixes most of these issues. For some reason, text formatting in the code file causes anywhere from 5-20 build errors.

**Comment by Kedar-27** [comment]
> @maqiqing This is mostly due to missing code in the JS or undeclared variables. Looking to fix this this month hopefuly!

Please fix this asap. Critical issue.

**Comment by YoomamaFTW** [comment]
It has been fixed. I'm hopefully going to publish this package on to SPM.

**Comment by Andrew-Chen-Wang** [comment]
Please let me know if there are any more issues. I'll be taking over maintainership for the time being and adding this to SPM. Hopefully I can make this package more extensible regarding the styling as well. Extending the JS can also be done via `runJS` but people might want to just include an entirely new file, which I can understand, so I'll be looking to do that as well.

**Comment by Andrew-Chen-Wang** [comment]
I've created an iOS example app and fixed some bugs. It'll be a slightly slow process in fixing everything since I'm pretty busy with school, but at least y'all can use this somewhat now.
